services:
  data_generator:
    build: ./data_generator
    volumes:
      - ./data_generator:/app  # Maps the entire data_generator directory
      - ./data_generator/generated_data:/app/generated_data  # Ensure generated_data is mapped for CSV files
    command: python /app/runall.py  # Run the data generation script
    environment:
      - TZ=UTC  # Set timezone to UTC

  radio_exporter:
    build: ./radio_exporter
    ports:
      - "8081:8081"  # Expose port for the radio exporter
    volumes:
      - ./data_generator/generated_data:/app/generated_data  # Ensure CSV files are accessible
    command: python /app/exporter.py  # Run the exporter script
    environment:
      - TZ=UTC  # Set timezone to UTC

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - TZ=UTC  # Set timezone to UTC

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"
